apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]
  
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "1s"
      flush_interval = "5s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = false
  
    [[inputs.kafka_consumer]]
      brokers = ["my-cluster-kafka-bootstrap:9092"]
      topics = ["wearables-lp"]
      max_message_len = 1000000
      consumer_fetch_default = "1MB"
      version = "4.0.0"
      data_format = "influx"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    
    [[outputs.influxdb_v2]]
      urls = [""]
      token = ""
      organization = "test"
      bucket = "test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf
      containers:
        - name: telegraf
          image: telegraf:1.36 # supports Kafka >= v4.x
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          ports:
            - containerPort: 8125
              name: metrics
              protocol: UDP
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
