apiVersion: v1
kind: ConfigMap
metadata:
  name: processors-star
data:
  fhir.star: |
    def apply(metric):
      
      if not metric.fields:
        return metric
    
      fhir = metric.fields
      
      new_metric = metric
      new_metric.measurement = fhir.get("resourceType", "FHIR-Resource")
      new_metric.tags["device"] = fhir.get("device", "")
      new_metric.tags["user"] = fhir.get("user", "")
      
      code_coding = fhir.get("code", {}).get("coding", [])
      if len(code_coding) > 0:
        new_metric.tags["code"] = code_coding[0].get("code", "")
        new_metric.tags["system"] = code_coding[0].get("system", "")
        new_metric.tags["display"] = code_coding[0].get("display", "")
    
      value_quantity = fhir.get("valueQuantity", {})
      new_metric.fields["value"] = value_quantity.get("value", 0)
      new_metric.fields["unit"] = value_quantity.get("unit", "")
      new_metric.fields["status"] = fhir.get("status", "")
    
      if "effectiveDateTime" in fhir:
        new_metric.time = fhir["effectiveDateTime"]
    
      return new_metric
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]
  
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "1s"
      flush_interval = "5s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = false
  
    [[inputs.kafka_consumer]]
      brokers = ["my-cluster-kafka-bootstrap:9092"]
      topics = ["wearables-fhir"]
      max_message_len = 1000000
      consumer_fetch_default = "1MB"
      version = "4.0.0"
      data_format = "influx"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    
    [[outputs.influxdb_v2]]
      urls = ["http://influx-service.test.svc.cluster.local:8086"]
      token = "WWC4CqjzlKvgQs_XGX9L-9tan8YfMvqXDCmYbKf4l80Hekp1a3_jJbZToWfY1mGKMUuA8CATNlI9Jap5MUZz-g=="
      organization = "test"
      bucket = "test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf
      containers:
        - name: telegraf
          image: telegraf:1.36 # supports Kafka >= v4.x
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: processors-star
              mountPath: /etc/telegraf/fhir.star
              subPath: fhir.star
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          ports:
            - containerPort: 8125
              name: metrics
              protocol: UDP
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: processors-star
          configMap:
            name: processors-star